# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: boskos-metrics
  namespace: test-pods
spec:
  selector:
    app: boskos-metrics
  ports:
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  loadBalancerIP: 104.197.27.114  # boskos-metrics
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-metrics
  labels:
    app: boskos-metrics
  namespace: test-pods
spec:
  selector:
    matchLabels:
      app: boskos-metrics
  replicas: 1
  template:
    metadata:
      labels:
        app: boskos-metrics
      namespace: test-pods
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: metrics
        image: gcr.io/k8s-prow/boskos/metrics:v20200206-f88edefe8
        args:
        - --resource-type=gce-project,gke-project,gpu-project,ingress-project,istio-project,scalability-presubmit-project,scalability-project,aws-account
        ports:
          - containerPort: 8080
            protocol: TCP
