apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor
  labels:
    app: boskos-janitor
  namespace: test-pods
spec:
  replicas: 16  # 16 distributed janitor instances for gke
  selector:
    matchLabels:
      app: boskos-janitor
  template:
    metadata:
      labels:
        app: boskos-janitor
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor
        image: gcr.io/k8s-prow/boskos/janitor:v20200226-fd34fd5f2
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=gke-project
        - --pool-size=20
        - --
        - --service_account=/etc/service-account/service-account.json
        - --hours=0
        volumeMounts:
        - mountPath: /etc/service-account
          name: service
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor-nongke
  labels:
    app: boskos-janitor-nongke
  namespace: test-pods
spec:
  replicas: 12 # 12 distributed janitor instances for non-gke
  selector:
    matchLabels:
      app: boskos-janitor-nongke
  template:
    metadata:
      labels:
        app: boskos-janitor-nongke
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor-nongke
        image: gcr.io/k8s-prow/boskos/janitor:v20200226-fd34fd5f2
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=gce-project,gpu-project,ingress-project,istio-project,scalability-presubmit-project,scalability-project
        - --pool-size=20
        - --
        - --service_account=/etc/service-account/service-account.json
        - --hours=0
        volumeMounts:
        - mountPath: /etc/service-account
          name: service
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor-aws
  labels:
    app: boskos-janitor-aws
  namespace: test-pods
spec:
  replicas: 4  # 4 distributed janitor instances
  selector:
    matchLabels:
      app: boskos-janitor-aws
  template:
    metadata:
      labels:
        app: boskos-janitor-aws
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor-aws
        image: gcr.io/k8s-prow/boskos/aws-janitor-boskos:v20200226-fd34fd5f2
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # TODO(fejta): consider a better project, but this is what service-account uses now
    iam.gke.io/gcp-service-account: pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
  name: boskos-janitor
  namespace: test-pods
